eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8899
spring:
  application:
    name: service-zuul
zuul:
  routes:
    mall-manager-ms:
      path: /ms/**
      service-id: mall-manager-ms